[build]
publish = "public"
command = "npm ci && grunt lunr-index && hugo --gc --minify"

[build.environment]
  NODE_VERSION = "14"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm ci && grunt lunr-index && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
NODE_VERSION = "14"

[context.deploy-preview]
command = "npm ci && grunt lunr-index && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"
NODE_VERSION = "14"

[context.branch-deploy]
command = "npm ci && grunt lunr-index && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"
NODE_VERSION = "14"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/de"
  status = 301
  force = false
  conditions = {Country = ["de","at","ch"]}
