---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/en/press
  label: Press EN
- type: heading
  label: Content
- type: directory
  path: content/en
  label: Pages EN
  create: documents
  match: "*"
  templates:
  - blocks
- type: directory
  path: content/de
  label: Pages DE
  create: documents
  match: "*"
  templates:
  - blocks
- type: directory
  path: content/en/posts
  label: Posts EN
  create: documents
  match: "*"
  templates:
  - blog-post
- type: directory
  path: content/de/posts
  label: Posts DE
  create: documents
  match: "*"
  templates:
  - blog-post
- type: directory
  path: content/en/docs
  label: Docs EN
  create: documents
  match: "*"
  templates:
  - documentation-post
- type: directory
  path: content/de/docs
  label: Docs DE
  create: documents
  match: "*"
  templates:
  - documentation-post
- type: directory
  path: content/en/tutorials
  label: Tutorials EN
  create: documents
  match: "*"
  templates:
  - documentation-post
- type: directory
  path: content/de/tutorials
  label: Tutorials DE
  create: documents
  match: "*"
  templates:
  - documentation-post
- type: document
  path: data/authors.yml
  label: Authors
- type: document
  path: data/videos.yml
  label: Videos
- type: document
  path: data/live.yml
  label: goat-application
- type: document
  path: data/docs.yml
  label: Docs Sections
- type: document
  path: data/tutorials.yml
  label: Tutorial Sections
- type: heading
  label: Settings
- type: document
  path: config.toml
  label: Config
- type: directory
  path: i18n
  label: String Translation
  create: documents
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
